# Generated by Django 3.0.5 on 2020-11-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toUsername', models.CharField(max_length=30)),
                ('fromUsername', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('movieId', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('Time', models.TimeField(default=None)),
                ('Date', models.DateField(default=None)),
                ('addTime', models.TimeField(auto_now=True)),
                ('addDate', models.DateField(auto_now=True)),
            ],
        ),
    ]
