# Generated by Django 3.0.5 on 2020-11-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='movieTitle',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
