# Generated by Django 3.0.5 on 2020-11-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_user_id', models.CharField(max_length=30)),
                ('movie_id', models.IntegerField(default=0)),
                ('review', models.CharField(blank=True, max_length=300)),
                ('rating', models.FloatField(default=0.0)),
                ('wishlist', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('watched', models.BooleanField(default=False)),
                ('review_time', models.TimeField(auto_now=True)),
                ('review_date', models.DateField(auto_now=True)),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
                ('follow', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('review_user_id', 'movie_id')},
            },
        ),
    ]
