# Generated by Django 3.0.5 on 2020-10-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=300)),
                ('rating', models.FloatField()),
                ('wishlist', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=None)),
                ('watched', models.BooleanField(default=False)),
                ('review_time', models.TimeField(auto_now=True)),
                ('review_date', models.DateField(auto_now=True)),
                ('upvote_count', models.IntegerField(default=0)),
                ('downvote_count', models.IntegerField(default=0)),
                ('follow', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movie_review.movies', to_field='movie_id')),
                ('review_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='profile.UserProfile', to_field='username')),
            ],
            options={
                'unique_together': {('review_user', 'movie')},
            },
        ),
    ]
