# Generated by Django 3.0.5 on 2020-11-14 00:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0002_auto_20201112_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='downvote_count',
        ),
        migrations.AddField(
            model_name='reviews',
            name='like_reviewers',
            field=multiselectfield.db.fields.MultiSelectField(default=None, max_length=200),
        ),
    ]
