# Generated by Django 3.0.5 on 2020-10-21 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6)),
                ('genres', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Horror', 'Horror'), ('Fiction', 'Fiction'), ('Comedy', 'Comedy'), ('Action', 'Action')], max_length=28, null=True)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('Chinkish', 'Chinkish'), ('Hindhi', 'Hindhi')], default=None, max_length=31)),
                ('banned', multiselectfield.db.fields.MultiSelectField(default=None, max_length=200)),
                ('watched', multiselectfield.db.fields.MultiSelectField(default=None, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
