export const moviesList=[
{'title': 'Avatar', 'description': 'In the 22nd century, a paraple', 'image': 'http://image.tmdb.org/t/p/original//6EiRUJpuoeQPghrs3YNktfnqOVh.jpg', 'price': '3.6'}, 
{'title': "Pirates of the Caribbean: At World's End", 'description': 'Captain Barbossa, long believe', 'image': 'http://image.tmdb.org/t/p/original//jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg', 'price': '3.5'}, 
{'title': 'Spectre', 'description': 'A cryptic message from Bond’s ', 'image': 'http://image.tmdb.org/t/p/original//672kUEMtTHcaVYSVY4eiHEliHFa.jpg', 'price': '3.1'}, 
{'title': 'The Dark Knight Rises', 'description': 'Following the death of Distric', 'image': 'http://image.tmdb.org/t/p/original//vzvKcPQ4o7TjWeGIn0aGC9FeVNu.jpg', 'price': '3.8'}, 
{'title': 'John Carter', 'description': 'John Carter is a war-weary, fo', 'image': 'http://image.tmdb.org/t/p/original//7GSSyUUgUEXm1rhmiPGSRuKoqnK.jpg', 'price': '3.0'},
{'title': 'Spider-Man 3', 'description': 'The seemingly invincible Spide', 'image': 'http://image.tmdb.org/t/p/original//2jLxKF73SAPkyhIWrnv67IH7kJ1.jpg', 'price': '3.0'},
{'title': 'Tangled', 'description': "When the kingdom's most wanted", 'image': 'http://image.tmdb.org/t/p/original//ym7Kst6a4uodryxqbGOxmewF235.jpg', 'price': '3.7'},
{'title': 'Avengers: Age of Ultron', 'description': 'When Tony Stark tries to jumps', 'image': 'http://image.tmdb.org/t/p/original//4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg', 'price': '3.6'},
{'title': 'Harry Potter and the Half-Blood Prince', 'description': 'As Harry begins his sixth year', 'image': 'http://image.tmdb.org/t/p/original//Ag21otqbeynZPGjEbzyr3X5Us0j.jpg', 'price': '3.7'},
{'title': 'Batman v Superman: Dawn of Justice', 'description': 'Fearing the actions of a god-l', 'image': 'http://image.tmdb.org/t/p/original//5UsK3grJvtQrtzEgqNlDljJW96w.jpg', 'price': '2.9'},
{'title': 'Superman Returns', 'description': 'Superman returns to discover h', 'image': 'http://image.tmdb.org/t/p/original//ijSsWy2RWxTJzw3UMwFbXkjr5ny.jpg', 'price': '2.7'},
{'title': 'Quantum of Solace', 'description': 'Quantum of Solace continues th', 'image': 'http://image.tmdb.org/t/p/original//5BzOOL7zknsZSUeJwSa9kGuzHCR.jpg', 'price': '3.0'},
{'title': "Pirates of the Caribbean: Dead Man's Chest", 'description': 'Captain Jack Sparrow works his', 'image': 'http://image.tmdb.org/t/p/original//AdRQGfT05z6L9gIpUpkh4McMmpm.jpg', 'price': '3.5'},
{'title': 'The Lone Ranger', 'description': 'The Texas Rangers chase down a', 'image': 'http://image.tmdb.org/t/p/original//b2je2ZybNIzAOL1K1WPbbT6zt2M.jpg', 'price': '3.0'},
{'title': 'Man of Steel', 'description': 'A young boy learns that he has', 'image': 'http://image.tmdb.org/t/p/original//7rIPjn5TUK04O25ZkMyHrGNPgLx.jpg', 'price': '3.2'},
{'title': 'The Chronicles of Narnia: Prince Caspian', 'description': 'One year after their incredibl', 'image': 'http://image.tmdb.org/t/p/original//qxz3WIyjZiSKUhaTIEJ3c1GcC9z.jpg', 'price': '3.1'}, 
{'title': 'The Avengers', 'description': 'When an unexpected enemy emerg', 'image': 'http://image.tmdb.org/t/p/original//RYMX2wcKCBAr24UyPD7xwmjaTn.jpg', 'price': '3.7'},
{'title': 'Pirates of the Caribbean: On Stranger Tides', 'description': 'Captain Jack Sparrow crosses p', 'image': 'http://image.tmdb.org/t/p/original//9zxsSzXx2UO3yNoS4j97vs4uOhc.jpg', 'price': '3.2'}, 
{'title': 'Men in Black 3', 'description': 'Agents J (Will Smith) and K (T', 'image': 'http://image.tmdb.org/t/p/original//e7kebbtwqzqam6l11aQNl7lXMs0.jpg', 'price': '3.1'}, 
{'title': 'The Hobbit: The Battle of the Five Armies', 'description': 'Immediately after the events o', 'image': 'http://image.tmdb.org/t/p/original//xT98tLqatZPQApyRmlPL12LtiWp.jpg', 'price': '3.5'},
{'title': 'The Amazing Spider-Man', 'description': 'Peter Parker is an outcast hig', 'image': 'http://image.tmdb.org/t/p/original//dQ8TOCYgP9pzQvSb1cmaalYqdb5.jpg', 'price': '3.2'},
{'title': 'Robin Hood', 'description': 'When soldier Robin happens upo', 'image': 'http://image.tmdb.org/t/p/original//9NS5QGOfck24yL3bZqWeW06PgPC.jpg', 'price': '3.1'},
{'title': 'The Hobbit: The Desolation of Smaug', 'description': 'The Dwarves, Bilbo and Gandalf', 'image': 'http://image.tmdb.org/t/p/original//xQYiXsheRCDBA39DOrmaw1aSpbk.jpg', 'price': '3.8'},
{'title': 'The Golden Compass', 'description': 'After overhearing a shocking s', 'image': 'http://image.tmdb.org/t/p/original//lyaS7S4emzEaYUcSnCvyqfJpOcA.jpg', 'price': '2.9'},
{'title': 'King Kong', 'description': 'In 1933 New York, an overly am', 'image': 'http://image.tmdb.org/t/p/original//6a2HY6UmD7XiDD3NokgaBAXEsD2.jpg', 'price': '3.3'},
{'title': 'Titanic', 'description': '84 years later, a 101-year-old', 'image': 'http://image.tmdb.org/t/p/original//9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', 'price': '3.8'},
{'title': 'Captain America: Civil War', 'description': 'Following the events of Age of', 'image': 'http://image.tmdb.org/t/p/original//rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg', 'price': '3.5'},
{'title': 'Battleship', 'description': 'When mankind beams a radio sig', 'image': 'http://image.tmdb.org/t/p/original//9b0Im7SfedHiajTwzSL9zGyBI7M.jpg', 'price': '2.8'},
{'title': 'Jurassic World', 'description': 'Twenty-two years after the eve', 'image': 'http://image.tmdb.org/t/p/original//rhr4y79GpxQF9IsfJItRXVaoGs4.jpg', 'price': '3.2'},
{'title': 'Skyfall', 'description': "When Bond's latest assignment ", 'image': 'http://image.tmdb.org/t/p/original//2pwwawlnti0BoluxFiksnVg5TZ7.jpg', 'price': '3.5'},
{'title': 'Spider-Man 2', 'description': 'Peter Parker is going through ', 'image': 'http://image.tmdb.org/t/p/original//olxpyq9kJAZ2NU1siLshhhXEPR7.jpg', 'price': '3.4'},
{'title': 'Iron Man 3', 'description': "When Tony Stark's world is tor", 'image': 'http://image.tmdb.org/t/p/original//qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg', 'price': '3.4'},
{'title': 'Alice in Wonderland', 'description': 'Alice, an unpretentious and in', 'image': 'http://image.tmdb.org/t/p/original//o0kre9wRCZz3jjSjaru7QU0UtFz.jpg', 'price': '3.2'},
{'title': 'X-Men: The Last Stand', 'description': 'When a cure is found to treat ', 'image': 'http://image.tmdb.org/t/p/original//9jDzVM003nH0NfQ57qMLHxcMQYU.jpg', 'price': '3.1'},
{'title': 'Monsters University', 'description': 'A look at the relationship bet', 'image': 'http://image.tmdb.org/t/p/original//y7thwJ7z5Bplv6vwl6RI0yteaDD.jpg', 'price': '3.5'},
{'title': 'Transformers: Revenge of the Fallen', 'description': 'Sam Witwicky leaves the Autobo', 'image': 'http://image.tmdb.org/t/p/original//6jcxahM7BDAAeKkP4IF8WLFsJ3K.jpg', 'price': '3.0'},
{'title': 'Transformers: Age of Extinction', 'description': 'As humanity picks up the piece', 'image': 'http://image.tmdb.org/t/p/original//jyzrfx2WaeY60kYZpPYepSjGz4S.jpg', 'price': '2.9'},
{'title': 'Oz: The Great and Powerful', 'description': 'Oscar Diggs, a small-time circ', 'image': 'http://image.tmdb.org/t/p/original//7lBgN59T5m1DaC9XcLkHOXdK9ax.jpg', 'price': '2.9'},
{'title': 'The Amazing Spider-Man 2', 'description': 'For Peter Parker, life is busy', 'image': 'http://image.tmdb.org/t/p/original//bU7nTmvmy0h3VUP01v1T2imgH6N.jpg', 'price': '3.2'},
{'title': 'TRON: Legacy', 'description': 'Sam Flynn, the tech-savvy and ', 'image': 'http://image.tmdb.org/t/p/original//vaQ2BDA8rP8vW2oj167TMhkOxvD.jpg', 'price': '3.1'},
{'title': 'Cars 2', 'description': 'Star race car Lightning McQuee', 'image': 'http://image.tmdb.org/t/p/original//okIz1HyxeVOMzYwwHUjH2pHi74I.jpg', 'price': '2.9'},
{'title': 'Green Lantern', 'description': 'For centuries, a small but pow', 'image': 'http://image.tmdb.org/t/p/original//fj21HwUprqjjwTdkKC1XZurRSpV.jpg', 'price': '2.5'},
{'title': 'Toy Story 3', 'description': 'Woody, Buzz, and the rest of A', 'image': 'http://image.tmdb.org/t/p/original//4cpGytCB0eqvRks4FAlJoUJiFPG.jpg', 'price': '3.8'},
{'title': 'Terminator Salvation', 'description': 'All grown up in post-apocalypt', 'image': 'http://image.tmdb.org/t/p/original//gw6JhlekZgtKUFlDTezq3j5JEPK.jpg', 'price': '3.0'},
{'title': 'Furious 7', 'description': 'Deckard Shaw seeks revenge aga', 'image': 'http://image.tmdb.org/t/p/original//jPFsjmFlTFmpIY41BP3C4sVYOKw.jpg', 'price': '3.6'},
{'title': 'World War Z', 'description': 'Life for former United Nations', 'image': 'http://image.tmdb.org/t/p/original//pLMpv8ckcDP3kiEd2fhwY7XrjHz.jpg', 'price': '3.4'},
{'title': 'X-Men: Days of Future Past', 'description': 'The ultimate X-Men ensemble fi', 'image': 'http://image.tmdb.org/t/p/original//bvN8iUpHyBIvniUk4e52SUZMA7Z.jpg', 'price': '3.8'},
{'title': 'Star Trek Into Darkness', 'description': 'When the crew of the Enterpris', 'image': 'http://image.tmdb.org/t/p/original//Aim3kVNh1MPIxPEFeJrl9e9Uf1a.jpg', 'price': '3.7'},
{'title': 'Jack the Giant Slayer', 'description': 'The story of an ancient war th', 'image': 'http://image.tmdb.org/t/p/original//99hEINsok4hbJRJRk8nEJ53sNzd.jpg', 'price': '2.8'},
{'title': 'The Great Gatsby', 'description': 'An adaptation of F. Scott Fitz', 'image': 'http://image.tmdb.org/t/p/original//nwJbVKauPDgJVQgT7SQpVTVN4gA.jpg', 'price': '3.6'},
{'title': 'Prince of Persia: The Sands of Time', 'description': 'A rogue prince reluctantly joi', 'image': 'http://image.tmdb.org/t/p/original//lkp1GFmWyf7k2WKvKIQuuGyichI.jpg', 'price': '3.1'},
{'title': 'Pacific Rim', 'description': 'When legions of monstrous crea', 'image': 'http://image.tmdb.org/t/p/original//mmznhaQDwlHWpUwKuNxtQiubbmM.jpg', 'price': '3.4'},
{'title': 'Transformers: Dark of the Moon', 'description': 'Sam Witwicky takes his first t', 'image': 'http://image.tmdb.org/t/p/original//wzF3o2eulc5gmOIaNCViqO3nLzK.jpg', 'price': '3.0'},
{'title': 'Indiana Jones and the Kingdom of the Crystal Skull', 'description': 'Set during the Cold War, the S', 'image': 'http://image.tmdb.org/t/p/original//dkM0XxfYa6g6MFoFtjjXFY48jHE.jpg', 'price': '2.9'},
{'title': 'The Good Dinosaur', 'description': 'An epic journey into the world', 'image': 'http://image.tmdb.org/t/p/original//dM50iVbcnzQUIoc9TmUUk0SP4P4.jpg', 'price': '3.3'},
{'title': 'Brave', 'description': 'Brave is set in the mystical S', 'image': 'http://image.tmdb.org/t/p/original//fg57nIBn2xQw8JZKIX6AzMa3pEp.jpg', 'price': '3.4'},
{'title': 'Star Trek Beyond', 'description': 'The USS Enterprise crew explor', 'image': 'http://image.tmdb.org/t/p/original//65NVDW2LnHt2ko3m8ACxFo8E21f.jpg', 'price': '3.3'},
{'title': 'WALL·E', 'description': 'WALL·E is the last robot left ', 'image': 'http://image.tmdb.org/t/p/original//Agc6lw8pb6BIGVeguvdjDT0p9Mb.jpg', 'price': '3.9'},
{'title': 'Rush Hour 3', 'description': 'After an attempted assassinati', 'image': 'http://image.tmdb.org/t/p/original//iXsbAIZezI0gh0dnOnBbeFuG3AO.jpg', 'price': '3.0'},
{'title': '2012', 'description': 'Dr. Adrian Helmsley, part of a', 'image': 'http://image.tmdb.org/t/p/original//zaqam2RNscH5ooYFWInV6hjx6y5.jpg', 'price': '2.8'},
{'title': 'A Christmas Carol', 'description': 'Miser Ebenezer Scrooge is awak', 'image': 'http://image.tmdb.org/t/p/original//goHDZUnqZJ7FN4h48Qh6MzJNExl.jpg', 'price': '3.3'},
{'title': 'Jupiter Ascending', 'description': 'In a universe where human gene', 'image': 'http://image.tmdb.org/t/p/original//2NCcAZ3M3F0FxENYmammBknwpVn.jpg', 'price': '2.6'},
{'title': 'The Legend of Tarzan', 'description': 'Tarzan, having acclimated to l', 'image': 'http://image.tmdb.org/t/p/original//eJrfz178xBGlxjDGxnBXTzWWa4w.jpg', 'price': '2.8'},
{'title': 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'description': 'Siblings Lucy, Edmund, Susan a', 'image': 'http://image.tmdb.org/t/p/original//kzJip9vndXYSKQHCgekrgqbnUrA.jpg', 'price': '3.4'},
{'title': 'X-Men: Apocalypse', 'description': 'After the re-emergence of the ', 'image': 'http://image.tmdb.org/t/p/original//2mtQwJKVKQrZgTz49Dizb25eOQQ.jpg', 'price': '3.2'},
{'title': 'The Dark Knight', 'description': 'Batman raises the stakes in hi', 'image': 'http://image.tmdb.org/t/p/original//qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'price': '4.1'},
{'title': 'Up', 'description': 'Carl Fredricksen spent his ent', 'image': 'http://image.tmdb.org/t/p/original//rIfKIYMbwVlnAXOOaQRsm34GW3S.jpg', 'price': '3.9'}, 
{'title': 'Monsters vs Aliens', 'description': 'When Susan Murphy is unwitting', 'image': 'http://image.tmdb.org/t/p/original//iVei1uT1IkbKcM2JRca9KEoTRXM.jpg', 'price': '3.0'},
{'title': 'Iron Man', 'description': 'After being held captive in an', 'image': 'http://image.tmdb.org/t/p/original//78lPtwv72eTNqFW9COBYI0dWDJa.jpg', 'price': '3.7'},
{'title': 'Hugo', 'description': 'Hugo is an orphan boy living i', 'image': 'http://image.tmdb.org/t/p/original//vDAhBTIHvIoNOlgCfmLirVgUK2p.jpg', 'price': '3.5'},
{'title': 'Wild Wild West', 'description': 'Legless Southern inventor Dr. ', 'image': 'http://image.tmdb.org/t/p/original//3C5cZnIwQ6Wj4qGFKv0BBjimWro.jpg', 'price': '2.5'},
{'title': 'The Mummy: Tomb of the Dragon Emperor', 'description': "Archaeologist Rick O'Connell t", 'image': 'http://image.tmdb.org/t/p/original//A3acM1lX5PNWQa6r5qeMAJOxbnT.jpg', 'price': '2.6'},
{'title': 'Suicide Squad', 'description': 'From DC Comics comes the Suici', 'image': 'http://image.tmdb.org/t/p/original//xFw9RXKZDvevAGocgBK0zteto4U.jpg', 'price': '3.0'},
{'title': 'Evan Almighty', 'description': 'God contacts Congressman Evan ', 'image': 'http://image.tmdb.org/t/p/original//5vjH8oQFZXJ0gTOPsJKWidVsWmg.jpg', 'price': '2.6'},
{'title': 'Edge of Tomorrow', 'description': 'Major Bill Cage is an officer ', 'image': 'http://image.tmdb.org/t/p/original//uUHvlkLavotfGsNtosDy8ShsIYF.jpg', 'price': '3.8'},
{'title': 'Waterworld', 'description': 'In a futuristic world where th', 'image': 'http://image.tmdb.org/t/p/original//f4Q6BKm1lv9u5xoffbIIwrOYf6z.jpg', 'price': '3.0'},
{'title': 'G.I. Joe: The Rise of Cobra', 'description': 'From the Egyptian desert to de', 'image': 'http://image.tmdb.org/t/p/original//wEr0FAAKPjlZ63i2WuuB2ge8OWv.jpg', 'price': '2.8'},
{'title': 'Inside Out', 'description': 'Growing up can be a bumpy road', 'image': 'http://image.tmdb.org/t/p/original//lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg', 'price': '4.0'},
{'title': 'The Jungle Book', 'description': 'After a threat from the tiger ', 'image': 'http://image.tmdb.org/t/p/original//tOEOlmLP71IojeJ91dyJ9Nsb8O8.jpg', 'price': '3.4'},
{'title': 'Iron Man 2', 'description': 'With the world now aware of hi', 'image': 'http://image.tmdb.org/t/p/original//6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg', 'price': '3.3'},
{'title': 'Snow White and the Huntsman', 'description': 'After the Evil Queen marries t', 'image': 'http://image.tmdb.org/t/p/original//xUNnFwO7XfjvrQ2hFfIlPTwqzDk.jpg', 'price': '2.9'},
{'title': 'Maleficent', 'description': "The untold story of Disney's m", 'image': 'http://image.tmdb.org/t/p/original//ik8PugpL41s137RAWEGTAWu0dPo.jpg', 'price': '3.5'},
{'title': 'Dawn of the Planet of the Apes', 'description': 'A group of scientists in San F', 'image': 'http://image.tmdb.org/t/p/original//ie14Sm0hRI5f7Te2KIfU64NyCPr.jpg', 'price': '3.6'},
{'title': 'The Lovers', 'description': 'The Lovers is an epic romance ', 'image': 'http://image.tmdb.org/t/p/original//mr6fTXiw4UAe2dgYdrdIs0Wkqcj.jpg', 'price': '2.4'},
{'title': '47 Ronin', 'description': 'Based on the original 1941 mov', 'image': 'http://image.tmdb.org/t/p/original//xDHnmcroujCRG0ysYQaiswjbyHd.jpg', 'price': '3.0'},
{'title': 'Captain America: The Winter Soldier', 'description': 'After the cataclysmic events i', 'image': 'http://image.tmdb.org/t/p/original//tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg', 'price': '3.8'},
{'title': 'Shrek Forever After', 'description': 'A bored and domesticated Shrek', 'image': 'http://image.tmdb.org/t/p/original//6HrfPZtKcGmX2tUWW3cnciZTaSD.jpg', 'price': '3.0'},
{'title': 'Tomorrowland', 'description': 'Bound by a shared destiny, a b', 'image': 'http://image.tmdb.org/t/p/original//iHh0nVGVODAFduF6Q6njdSSCEfX.jpg', 'price': '3.1'},
{'title': 'Big Hero 6', 'description': 'The special bond that develops', 'image': 'http://image.tmdb.org/t/p/original//2mxS4wUimwlLmI1xp6QW6NSU361.jpg', 'price': '3.9'},
{'title': 'Wreck-It Ralph', 'description': 'Wreck-It Ralph is the 9-foot-t', 'image': 'http://image.tmdb.org/t/p/original//j8M1kHBAXa6KFNzGnWtdsVsLUro.jpg', 'price': '3.5'},
{'title': 'The Polar Express', 'description': 'When a doubting young boy take', 'image': 'http://image.tmdb.org/t/p/original//hc2NFfInDrOiIgIy8TTjEZTvSkz.jpg', 'price': '3.2'},
{'title': 'Independence Day: Resurgence', 'description': 'We always knew they were comin', 'image': 'http://image.tmdb.org/t/p/original//jzpvh0Ic7jL9GX4NLE1Tx2GUCrN.jpg', 'price': '2.5'},
{'title': 'How to Train Your Dragon', 'description': 'As the son of a Viking leader ', 'image': 'http://image.tmdb.org/t/p/original//ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg', 'price': '3.8'},
{'title': 'Terminator 3: Rise of the Machines', 'description': "It's been 10 years since John ", 'image': 'http://image.tmdb.org/t/p/original//vvevzdYIrk2636maNW4qeWmlPFG.jpg', 'price': '3.0'},
{'title': 'Guardians of the Galaxy', 'description': 'Light years from Earth, 26 yea', 'image': 'http://image.tmdb.org/t/p/original//r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg', 'price': '4.0'},
{'title': 'Interstellar', 'description': 'Interstellar chronicles the ad', 'image': 'http://image.tmdb.org/t/p/original//gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'price': '4.0'},
{'title': 'Inception', 'description': 'Cobb, a skilled thief who comm', 'image': 'http://image.tmdb.org/t/p/original//9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', 'price': '4.0'},
{'title': 'Shin Godzilla', 'description': 'From the mind behind Evangelio', 'image': 'http://image.tmdb.org/t/p/original//jPNShaWZMpVF0iQ7j1dvTuZLD20.jpg', 'price': '3.2'},
{'title': 'The Hobbit: An Unexpected Journey', 'description': 'Bilbo Baggins, a hobbit enjoyi', 'image': 'http://image.tmdb.org/t/p/original//yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg', 'price': '3.5'},
{'title': 'The Fast and the Furious', 'description': 'Domenic Toretto is a Los Angel', 'image': 'http://image.tmdb.org/t/p/original//5En3O5t9LG8PfRaNs3vKfMdjQ1B.jpg', 'price': '3.3'},
{'title': 'The Curious Case of Benjamin Button', 'description': 'Tells the story of Benjamin Bu', 'image': 'http://image.tmdb.org/t/p/original//26wEWZYt6yJkwRVkjcbwJEFh9IS.jpg', 'price': '3.6'},
{'title': 'X-Men: First Class', 'description': 'Before Charles Xavier and Erik', 'image': 'http://image.tmdb.org/t/p/original//5QId52kcNtbq6w2OS7smwTPFi2.jpg', 'price': '3.5'},
{'title': 'The Hunger Games: Mockingjay - Part 2', 'description': 'With the nation of Panem in a ', 'image': 'http://image.tmdb.org/t/p/original//fsacCfyb7njkcP5ltXUZiZED7lP.jpg', 'price': '3.3'},
{'title': "The Sorcerer's Apprentice", 'description': 'Balthazar Blake is a master so', 'image': 'http://image.tmdb.org/t/p/original//b5pIUsGll0418NyfNA5eYCI9aoK.jpg', 'price': '2.9'},
{'title': 'Poseidon', 'description': 'A packed cruise ship traveling', 'image': 'http://image.tmdb.org/t/p/original//cCx2Ead8KoZhHofsAAr7tyrjfDo.jpg', 'price': '2.8'},
{'title': 'Alice Through the Looking Glass', 'description': "In the sequel to Tim Burton's ", 'image': 'http://image.tmdb.org/t/p/original//uGsjYHPZ0NbI7GHrHlq98D4kFYB.jpg', 'price': '3.2'},
{'title': 'Shrek the Third', 'description': 'The King of Far Far Away has d', 'image': 'http://image.tmdb.org/t/p/original//jaNe16gE9zdAYyVwRqmlmRKshHm.jpg', 'price': '3.0'},
{'title': 'Warcraft', 'description': 'The peaceful realm of Azeroth ', 'image': 'http://image.tmdb.org/t/p/original//k3a41SS1q5xmbvzPvzTIfG7GDlp.jpg', 'price': '3.1'},
{'title': 'Terminator Genisys', 'description': 'The year is 2029. John Connor,', 'image': 'http://image.tmdb.org/t/p/original//oZRVDpNtmHk8M1VYy1aeOWUXgbC.jpg', 'price': '2.9'},
{'title': 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'description': 'This time around Edmund and Lu', 'image': 'http://image.tmdb.org/t/p/original//pP27zlm9yeKrCeDZLFLP2HKELot.jpg', 'price': '3.1'},
{'title': 'Pearl Harbor', 'description': 'The lifelong friendship betwee', 'image': 'http://image.tmdb.org/t/p/original//ftkKVbk4sQEcekuaGJvpvXcNs32.jpg', 'price': '3.3'},
{'title': 'Transformers', 'description': 'Young teenager, Sam Witwicky b', 'image': 'http://image.tmdb.org/t/p/original//6eehp9I54syN3x753XMqjKz8M3F.jpg', 'price': '3.3'},
{'title': 'Alexander', 'description': 'Alexander, the King of Macedon', 'image': 'http://image.tmdb.org/t/p/original//faVET7EulRCnYRwi65jnHqR2di8.jpg', 'price': '2.8'},
{'title': 'Harry Potter and the Order of the Phoenix', 'description': 'Returning for his fifth year o', 'image': 'http://image.tmdb.org/t/p/original//g6n8G0xPnBVUIKKK41sNmbZB5h4.jpg', 'price': '3.7'},
{'title': 'Harry Potter and the Goblet of Fire', 'description': 'Harry starts his fourth year a', 'image': 'http://image.tmdb.org/t/p/original//fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg', 'price': '3.8'},
{'title': 'Hancock', 'description': 'Hancock is a down-and-out supe', 'image': 'http://image.tmdb.org/t/p/original//7DyuV2G0hLEqHeueDfOqhZ2DVut.jpg', 'price': '3.1'},
{'title': 'I Am Legend', 'description': 'Robert Neville is a scientist ', 'image': 'http://image.tmdb.org/t/p/original//iPDkaSdKk2jRLTM65UOEoKtsIZ8.jpg', 'price': '3.5'},
{'title': 'Charlie and the Chocolate Factory', 'description': 'A young boy wins a tour throug', 'image': 'http://image.tmdb.org/t/p/original//wfGfxtBkhBzQfOZw4S8IQZgrH0a.jpg', 'price': '3.4'}, 
{'title': 'Ratatouille', 'description': 'A rat named Remy dreams of bec', 'image': 'http://image.tmdb.org/t/p/original//npHNjldbeTHdKKw28bJKs7lzqzj.jpg', 'price': '3.8'},
{'title': 'Batman Begins', 'description': 'Driven by tragedy, billionaire', 'image': 'http://image.tmdb.org/t/p/original//1P3ZyEq02wcTMd3iE4ebtLvncvH.jpg', 'price': '3.8'},
{'title': 'Madagascar: Escape 2 Africa', 'description': 'Alex, Marty, Melman, Gloria, K', 'image': 'http://image.tmdb.org/t/p/original//9lfNdHVfd37R1GszeH5ZcWzkb14.jpg', 'price': '3.1'},
{'title': 'Night at the Museum: Battle of the Smithsonian', 'description': 'Hapless museum night watchman ', 'image': 'http://image.tmdb.org/t/p/original//rBm8YJUH1Sh0yGn2w5MEjOhwP3F.jpg', 'price': '3.0'},
{'title': 'X-Men Origins: Wolverine', 'description': 'After seeking to live a normal', 'image': 'http://image.tmdb.org/t/p/original//8TItaEDL9lRCVcGMkYFluceD2Od.jpg', 'price': '3.1'},
{'title': 'The Matrix Revolutions', 'description': 'The human city of Zion defends', 'image': 'http://image.tmdb.org/t/p/original//fgm8OZ7o4G1G1I9EeGcb85Noe6L.jpg', 'price': '3.2'},
{'title': 'Frozen', 'description': 'Young princess Anna of Arendel', 'image': 'http://image.tmdb.org/t/p/original//kgwjIb2JDHRhNk13lmSxiClFjVk.jpg', 'price': '3.6'}, 
{'title': 'The Matrix Reloaded', 'description': 'Six months after the events de', 'image': 'http://image.tmdb.org/t/p/original//jBegA6V243J6HUnpcOILsRvBnGb.jpg', 'price': '3.4'},
{'title': 'Thor: The Dark World', 'description': 'Thor fights to restore order a', 'image': 'http://image.tmdb.org/t/p/original//wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg', 'price': '3.4'},
{'title': 'Mad Max: Fury Road', 'description': 'An apocalyptic story set in th', 'image': 'http://image.tmdb.org/t/p/original//8tZYtuWezp8JbcsvHYO0O46tFbo.jpg', 'price': '3.6'},
{'title': 'Angels & Demons', 'description': 'Harvard symbologist Robert Lan', 'image': 'http://image.tmdb.org/t/p/original//uRBapeuwV8yy4in4BkETHBDmWkH.jpg', 'price': '3.2'},
{'title': 'Thor', 'description': "Against his father Odin's will", 'image': 'http://image.tmdb.org/t/p/original//prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg', 'price': '3.3'}, 
{'title': 'Bolt', 'description': 'Bolt is the star of the bigges', 'image': 'http://image.tmdb.org/t/p/original//z9VHoUcZ1GiH3f3qYz7Me7Zc1Fd.jpg', 'price': '3.1'}, 
{'title': 'G-Force', 'description': 'A team of trained secret agent', 'image': 'http://image.tmdb.org/t/p/original//jpjG88kTrK7mHnRx4cpLHh8YZwr.jpg', 'price': '2.5'},
{'title': 'Wrath of the Titans', 'description': 'A decade after his heroic defe', 'image': 'http://image.tmdb.org/t/p/original//oYYLGGLEXgpqmbaL1da02qibY1S.jpg', 'price': '2.8'},
{'title': 'Dark Shadows', 'description': 'Vampire Barnabas Collins is in', 'image': 'http://image.tmdb.org/t/p/original//eteQ3gyMpA0oiWcYX4XoXGry0cB.jpg', 'price': '2.9'},
{'title': 'Mission: Impossible - Rogue Nation', 'description': 'Ethan and team take on their m', 'image': 'http://image.tmdb.org/t/p/original//oUDKymEL932AeHyl4A4ee8zuBLF.jpg', 'price': '3.5'},
{'title': 'The Wolfman', 'description': 'Lawrence Talbot, an American m', 'image': 'http://image.tmdb.org/t/p/original//guedPkxdWYoi8zv9l05uWbKtbQ5.jpg', 'price': '2.8'},
{'title': 'Bee Movie', 'description': 'Barry B. Benson, a bee who has', 'image': 'http://image.tmdb.org/t/p/original//rYBaXgvTKFS8iZC7Wr8SMomSauQ.jpg', 'price': '2.9'},
{'title': 'Kung Fu Panda 2', 'description': 'Po is now living his dream as ', 'image': 'http://image.tmdb.org/t/p/original//mtqqD00vB4PGRt20gWtGqFhrkd0.jpg', 'price': '3.4'},
{'title': 'The Last Airbender', 'description': 'The story follows the adventur', 'image': 'http://image.tmdb.org/t/p/original//zgwRTYWEEPivTwjB9S03HtmMcbM.jpg', 'price': '2.4'},
{'title': 'Mission: Impossible III', 'description': 'Retired from active duty to tr', 'image': 'http://image.tmdb.org/t/p/original//5l0hS4A119jCA1A02XsFZHq1uRD.jpg', 'price': '3.2'},
{'title': 'White House Down', 'description': 'Capitol Policeman John Cale ha', 'image': 'http://image.tmdb.org/t/p/original//hXLScIERphkTsMGdfKKvF4p4SPB.jpg', 'price': '3.2'},
{'title': 'Mars Needs Moms', 'description': 'When Martians suddenly abduct ', 'image': 'http://image.tmdb.org/t/p/original//lOKqLd0ud1wdwaPK5h6bGNZIVLT.jpg', 'price': '2.8'},
{'title': 'Flushed Away', 'description': 'London high-society mouse, Rod', 'image': 'http://image.tmdb.org/t/p/original//885fQK8aQw8sQiQVco9ffQZvJ9t.jpg', 'price': '3.0'},
{'title': 'Pan', 'description': 'Living a bleak existence at a ', 'image': 'http://image.tmdb.org/t/p/original//cjcrkPeQkrkEVYrd3lHWJbfBdrv.jpg', 'price': '3.0'},
{'title': 'Mr. Peabody & Sherman', 'description': 'A young boy and his dog, who h', 'image': 'http://image.tmdb.org/t/p/original//zfM3kcF6IiHkM84JsMFYAnKnEuh.jpg', 'price': '3.4'},
{'title': 'Troy', 'description': 'In year 1250 B.C. during the l', 'image': 'http://image.tmdb.org/t/p/original//kWj4RJzZeJGeyGA3DVGQiNkUjkt.jpg', 'price': '3.5'},
{'title': "Madagascar 3: Europe's Most Wanted", 'description': 'Alex, Marty, Gloria and Melman', 'image': 'http://image.tmdb.org/t/p/original//ekraj4ksvIKeuvQVEevEJkuybZd.jpg', 'price': '3.2'},
{'title': 'Die Another Day', 'description': 'Bond takes on a North Korean l', 'image': 'http://image.tmdb.org/t/p/original//bZmGqOhMhaLn8AoFMvFDct4tbrL.jpg', 'price': '2.9'},
{'title': 'Ghostbusters', 'description': 'Following a ghost invasion of ', 'image': 'http://image.tmdb.org/t/p/original//wJmWliwXIgZOCCVOcGRBhce7xPS.jpg', 'price': '2.6'},
{'title': 'Armageddon', 'description': 'When an asteroid threatens to ', 'image': 'http://image.tmdb.org/t/p/original//eTM3qtGhDU8cvjpoa6KEt5E2auU.jpg', 'price': '3.2'},
{'title': 'Men in Black II', 'description': 'Kay and Jay reunite to provide', 'image': 'http://image.tmdb.org/t/p/original//enA22EPyzc2WQ1VVyY7zxresQQr.jpg', 'price': '3.0'},
{'title': 'Beowulf', 'description': '6th-century Scandinavian warri', 'image': 'http://image.tmdb.org/t/p/original//7QsWYyJAV97N9jOh21pdRIqJeJq.jpg', 'price': '2.8'},
{'title': 'Kung Fu Panda 3', 'description': 'Continuing his "legendary adve', 'image': 'http://image.tmdb.org/t/p/original//nlr2oxuYsHXt0wdtmzaOuVBoNC0.jpg', 'price': '3.4'},
{'title': 'Mission: Impossible - Ghost Protocol', 'description': 'In the 4th installment of the ', 'image': 'http://image.tmdb.org/t/p/original//7GCKNRbzcA4rJXAKoE8KS9IDnZP.jpg', 'price': '3.4'},
{'title': 'Rise of the Guardians', 'description': 'When an evil spirit known as P', 'image': 'http://image.tmdb.org/t/p/original//kUBkmlWriPbNMijL2m3LtmPYPTb.jpg', 'price': '3.5'},
{'title': 'Fun with Dick and Jane', 'description': 'After Dick Harper loses his jo', 'image': 'http://image.tmdb.org/t/p/original//1NBVGBi8Z6MhJBAJ5SuRMqP7o3T.jpg', 'price': '3.0'},
{'title': 'The Last Samurai', 'description': 'Nathan Algren is an American h', 'image': 'http://image.tmdb.org/t/p/original//wwCOJtRAkn287NbWUtOTlYbiL4Z.jpg', 'price': '3.6'},
{'title': 'Exodus: Gods and Kings', 'description': 'The defiant leader Moses rises', 'image': 'http://image.tmdb.org/t/p/original//uaDj37JtvLan9tihxZ18e6qL33b.jpg', 'price': '2.8'},
{'title': 'Star Trek', 'description': 'The fate of the galaxy rests i', 'image': 'http://image.tmdb.org/t/p/original//hN2ZtF3Uw6mhIHZiqL0SKzELtKn.jpg', 'price': '3.7'},
{'title': 'Spider-Man', 'description': 'After being bitten by a geneti', 'image': 'http://image.tmdb.org/t/p/original//gh4cZbhZxyTbgxQPxD0dOudNPTn.jpg', 'price': '3.4'},
{'title': 'How to Train Your Dragon 2', 'description': 'The thrilling second chapter o', 'image': 'http://image.tmdb.org/t/p/original//d13Uj86LdbDLrfDoHR5aDOFYyJC.jpg', 'price': '3.8'},
{'title': 'Gods of Egypt', 'description': 'A common thief joins a mythica', 'image': 'http://image.tmdb.org/t/p/original//zpXkim56DyQIbZPpMyTqygo81Kc.jpg', 'price': '2.6'},
{'title': 'Stealth', 'description': 'Deeply ensconced in a top-secr', 'image': 'http://image.tmdb.org/t/p/original//eVmOkUrEIRm6DKusKbI1gVS8paQ.jpg', 'price': '2.5'},
{'title': 'Watchmen', 'description': 'In a gritty and alternate 1985', 'image': 'http://image.tmdb.org/t/p/original//aZvOkdo203bm1kpcY0A0Tn074ER.jpg', 'price': '3.5'},
{'title': 'Lethal Weapon 4', 'description': 'In the combustible action fran', 'image': 'http://image.tmdb.org/t/p/original//qc0GVMhZk44icQdynIin0xkE9YZ.jpg', 'price': '3.1'},
{'title': 'Hulk', 'description': 'Bruce Banner, a genetics resea', 'image': 'http://image.tmdb.org/t/p/original//qnngKqAcqfH2pBxDoKu5lxzSbTo.jpg', 'price': '2.6'}, 
{'title': 'G.I. Joe: Retaliation', 'description': 'Framed for crimes against the ', 'image': 'http://image.tmdb.org/t/p/original//9g8DS1SoV77GzQWjxOeAvt4ZE3P.jpg', 'price': '2.7'}, 
{'title': 'Sahara', 'description': 'Scouring the ocean depths for ', 'image': 'http://image.tmdb.org/t/p/original//32JjbBgpUj0AkhUMHNZAB56r4NM.jpg', 'price': '2.9'},
{'title': 'Final Fantasy: The Spirits Within', 'description': 'Led by a strange dream, scient', 'image': 'http://image.tmdb.org/t/p/original//cJlEv3xULhBt6WvjYEntBg3ReEw.jpg', 'price': '3.0'},
{'title': 'Captain America: The First Avenger', 'description': 'Predominantly set during World', 'image': 'http://image.tmdb.org/t/p/original//vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg', 'price': '3.3'},
{'title': 'The World Is Not Enough', 'description': 'Greed, revenge, world dominanc', 'image': 'http://image.tmdb.org/t/p/original//3lLFKiVPUoENZuCD19AaXZqeGB0.jpg', 'price': '3.0'},
{'title': 'Master and Commander: The Far Side of the World', 'description': 'After an abrupt and violent en', 'image': 'http://image.tmdb.org/t/p/original//s1cVTQEZYn4nSjZLnFbzLP0j8y2.jpg', 'price': '3.5'},
{'title': 'The Twilight Saga: Breaking Dawn - Part 2', 'description': 'After the birth of Renesmee, t', 'image': 'http://image.tmdb.org/t/p/original//jHE7WUf3FDod8vw3O3twh0JVZun.jpg', 'price': '3.0'},
{'title': 'Happy Feet Two', 'description': 'Mumble the penguin has a probl', 'image': 'http://image.tmdb.org/t/p/original//2gWiQ4mn85jcXtREVePlVViupeV.jpg', 'price': '2.9'},
{'title': 'The Incredible Hulk', 'description': 'Scientist Bruce Banner scours ', 'image': 'http://image.tmdb.org/t/p/original//2nBpExDoInX3VreBsIm9qOTqXs8.jpg', 'price': '3.0'},
{'title': 'The BFG', 'description': 'The BFG is no ordinary bone-cr', 'image': 'http://image.tmdb.org/t/p/original//4zawxGJIH43DcoGG9Ui0WoIcrQC.jpg', 'price': '3.0'},
{'title': 'The Revenant', 'description': 'In the 1820s, a frontiersman, ', 'image': 'http://image.tmdb.org/t/p/original//ji3ecJphATlVgWNY0B0RVXZizdf.jpg', 'price': '3.6'},
{'title': 'Turbo', 'description': 'The tale of an ordinary garden', 'image': 'http://image.tmdb.org/t/p/original//aE3A98CfBWVReurJqpOBFbzIwMf.jpg', 'price': '3.0'},
{'title': 'Rango', 'description': 'When Rango, a lost family pet,', 'image': 'http://image.tmdb.org/t/p/original//m5kz9dXHhAqzxknwuACvcgJmQSH.jpg', 'price': '3.3'},
{'title': 'Penguins of Madagascar', 'description': 'Skipper, Kowalski, Rico and Pr', 'image': 'http://image.tmdb.org/t/p/original//gbtwoYMWlG0HZe7sDaTOoijtXCu.jpg', 'price': '3.2'},
{'title': 'The Bourne Ultimatum', 'description': 'Bourne is brought out of hidin', 'image': 'http://image.tmdb.org/t/p/original//d4DuphCHCjVUyffExnK5nLbn39K.jpg', 'price': '3.6'},
{'title': 'Kung Fu Panda', 'description': 'When the Valley of Peace is th', 'image': 'http://image.tmdb.org/t/p/original//wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg', 'price': '3.5'},
{'title': 'Ant-Man', 'description': 'Armed with the astonishing abi', 'image': 'http://image.tmdb.org/t/p/original//rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg', 'price': '3.5'},
{'title': 'The Hunger Games: Catching Fire', 'description': 'Katniss Everdeen has returned ', 'image': 'http://image.tmdb.org/t/p/original//7c1JtraYsjMMnk8Md0IMoyRzqZJ.jpg', 'price': '3.7'},
{'title': 'Home', 'description': 'When Earth is taken over by th', 'image': 'http://image.tmdb.org/t/p/original//usFenYnk6mr8C62dB1MoAfSWMGR.jpg', 'price': '3.4'},
{'title': 'War of the Worlds', 'description': 'Ray Ferrier is a divorced dock', 'image': 'http://image.tmdb.org/t/p/original//6Biy7R9LfumYshur3YKhpj56MpB.jpg', 'price': '3.1'},
{'title': 'Bad Boys II', 'description': 'Out-of-control, trash-talking ', 'image': 'http://image.tmdb.org/t/p/original//yCvB5fG5aEPqa1St7ihY6KEAsHD.jpg', 'price': '3.1'},
{'title': 'Puss in Boots', 'description': 'Long before he even met Shrek,', 'image': 'http://image.tmdb.org/t/p/original//eufJ36oQCauDc427ewaEvQrhZ6i.jpg', 'price': '3.2'},
{'title': 'Salt', 'description': 'As a CIA officer, Evelyn Salt ', 'image': 'http://image.tmdb.org/t/p/original//ppXyhOe8UCEOrBRSYqE3SkHwrcR.jpg', 'price': '3.1'},
{'title': 'Noah', 'description': 'A man who suffers visions of a', 'image': 'http://image.tmdb.org/t/p/original//trtD17IqSWV9Nbn4OILztc9GuCX.jpg', 'price': '2.8'},
{'title': 'The Adventures of Tintin', 'description': 'Intrepid young reporter, Tinti', 'image': 'http://image.tmdb.org/t/p/original//mKYkNro2btaWMsnYSuyqrBdHQo3.jpg', 'price': '3.4'},
{'title': 'Harry Potter and the Prisoner of Azkaban', 'description': 'Harry, Ron and Hermione return', 'image': 'http://image.tmdb.org/t/p/original//v0wMKEEGaNc9evdqGYfIvoWXh24.jpg', 'price': '3.9'},
{'title': 'Australia', 'description': 'Set in northern Australia befo', 'image': 'http://image.tmdb.org/t/p/original//45X7LFsgYvdEgFCkXSZCQOZMuJX.jpg', 'price': '3.1'},
{'title': 'After Earth', 'description': 'One thousand years after catac', 'image': 'http://image.tmdb.org/t/p/original//iXMvYIlzzJBs352CfeiQcBvovZt.jpg', 'price': '2.5'},
{'title': 'Dinosaur', 'description': 'An orphaned dinosaur raised by', 'image': 'http://image.tmdb.org/t/p/original//rSje3FS7ycJSglowlngjsvDt7vO.jpg', 'price': '3.1'},
{'title': 'Night at the Museum: Secret of the Tomb', 'description': 'When the magic powers of The T', 'image': 'http://image.tmdb.org/t/p/original//xwgy305K6qDs3D20xUO4OZu1HPY.jpg', 'price': '3.0'},
{'title': 'Megamind', 'description': 'Bumbling supervillain Megamind', 'image': 'http://image.tmdb.org/t/p/original//7l5OY9oeJyaB2XJKrg0du7pmi1C.jpg', 'price': '3.4'},
{'title': "Harry Potter and the Philosopher's Stone", 'description': 'Harry Potter has lived under t', 'image': 'http://image.tmdb.org/t/p/original//wuMc08IPKEatf9rnMNXvIDxqP4W.jpg', 'price': '3.8'},
{'title': 'R.I.P.D.', 'description': 'A recently slain cop joins a t', 'image': 'http://image.tmdb.org/t/p/original//fQ7CI5zmmhZlHuYBFKgK9w4hwlS.jpg', 'price': '2.7'},
{'title': 'Pirates of the Caribbean: The Curse of the Black Pearl', 'description': 'Jack Sparrow, a freewheeling 1', 'image': 'http://image.tmdb.org/t/p/original//z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg', 'price': '3.8'}
]

export default {moviesList};